version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
